name: Publish

on:
  push:
    tags:
      - "v*"

permissions:
  contents: read

env:
  RUSTFLAGS: -Dwarnings

jobs:
  publish:
    name: Publish to crates.io
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Verify workspace version matches tag
        run: |
          TAG_VERSION=${GITHUB_REF#refs/tags/v}
          WORKSPACE_VERSION=$(grep '^version = ' Cargo.toml | sed 's/version = "\(.*\)"/\1/')
          if [ "$WORKSPACE_VERSION" != "$TAG_VERSION" ]; then
            echo "Error: Workspace version ($WORKSPACE_VERSION) does not match tag version ($TAG_VERSION)"
            exit 1
          fi
          echo "Version check passed: $WORKSPACE_VERSION"
      - name: Publish eager2-core
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish -p eager2-core
      - name: Wait for crates.io to update
        run: sleep 30s
      - name: Publish eager2
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
        run: cargo publish -p eager2
